"""Update user model

Revision ID: 093bc1acd8d6
Revises: e935357f6c6f
Create Date: 2023-12-15 21:07:05.236184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '093bc1acd8d6'
down_revision = 'e935357f6c6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
