"""Add user table for auth

Revision ID: 16934cc055b9
Revises: d897f9932843
Create Date: 2023-11-24 11:23:36.207121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16934cc055b9'
down_revision = 'd897f9932843'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('profile_pic', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    with op.batch_alter_table('data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meta', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data', schema=None) as batch_op:
        batch_op.drop_column('meta')

    op.drop_table('users')
    # ### end Alembic commands ###
